### ISSUE TITLE
Team City Issues

### ISSUE THREAD

**Issue by ianjohngraham** [rossrowe/sauce-ci-java-demo#4]
Hi,

I've followed the steps below which describe how to setup Team city with Saunce labs using this project. All works up to the point when it tries to build the SauceConnectTest.java file. 

I get the following message:

Compilation failure
\TeamCity\BuildAgent2\work\e0e9742778ff93c\src\test\java\SauceConnectTest.java:[1,-1] cannot access com.saucelabs.common.SauceOnDemandAuthentication
bad class file: C:\.m2\repository\com\saucelabs\sauce_java_common\1.0.18\sauce_java_common-1.0.18.jar(com/saucelabs/common/SauceOnDemandAuthentication.class)
class file has wrong version 50.0, should be 49.0.

Any idea what could be wrong and what libraries are incorrect?

https://docs.saucelabs.com/ci-integrations/teamcity/#teamcity-configuration-for-a-java-based-project

**Comment by rossrowe** [comment]
Hi, I've just pushed some changes to the project which reference the latest version of the sauce-java libraries, can you see if they resolve the issue?

**Comment by ianjohngraham** [comment]
Hi Ross,
Thanks for doing that. I pulled down the latest code base again and no change though as far as I can see- still the same error message.
I'm using the following setup:

JDK 1.5.022
Team city 8.0.6 (build 27767)

Any idea if I'm missing something?

Thanks
Ian

**Comment by rossrowe** [comment]
Would you be able to try JDK 7 rather than JDK 1.5?  I'm pretty sure the
code is using JDK 7 features which is probably why it's not working for you

**Comment by ianjohngraham** [comment]
Great, switched to JDK 7 and all good now. Thanks very much for your help.
